### PR TITLE
🐛 Fix: 배지페이지 헤더/푸터 수정

### LINKED ISSUE #102: 🐞 [Bug] 배지 헤더 수정
# 🐞 어떤 버그인가요?

헤더/푸터와 내용이 겹쳐서 보임

## 📝 어떤 상황에서 발생한 버그인가요?

- **Given**: 페이지 상단에 고정된 헤더와 하단에 고정된 푸터가 있음
- **When**: 페이지를 로드할 때
- **Then**: 본문 첫 번째 섹션이 헤더와 겹쳐서 가려짐

## 🎯 예상 결과

헤더/푸터 영역 높이만큼 제외하고 내용이 보이며, 겹침 없이 정상적으로 표시되어야 함

### PR DESCRIPTION
**Pull request by zo0o0**
## 🚀 관련 이슈

- close #102 

## 🔑 작업 내용

배지페이지 헤더/푸터 수정

## 📷 스크린샷

image

image

## Summary by CodeRabbit

* **Style**
  * Header now appears above the content area on the My Badge page.
  * Content area gains proper top padding and becomes vertically scrollable.
  * Layout width and horizontal padding adjusted for better centering and readability.
  * Action footer is now fixed at the bottom with improved layering, staying visible while scrolling.
  * Added bottom spacing to prevent content from being hidden behind the fixed footer.
  * Minor visual refinements; no changes to page logic or interactions.

### CODE REVIEW

File: src/pages/auth/mypage/mybadge.tsx [hunk 1]
```diff
@@ -61,8 +61,8 @@ const Mybadge = () => {
 
   return (
     <div ref={wrapperRef} className={S.container}>
+      <Header title="MY 배지" />
       <div className={S.topContainer}>
-        <Header title="MY 배지" />
         <div className={S.titleContainer}>
           <div className={S.title}>대표 배지</div>
```
Comment (sheepyis) [inline src/pages/auth/mypage/mybadge.tsx:67]: 대표 배지 글씨가 헤더랑 좌측 정렬이 안맞아보이는데 확인 부탁드립니다!

**Review by sheepyis — APPROVED** [review]

**Review by gpdnjs8 — APPROVED** [review]
